<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Projet;
use AppBundle\Form\ProjetType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ProjetController extends Controller
{
    /**
     * @Route("/backend/newProjet", name="new_projet")
     */
    public function newProjetAction(Request $request)
    {
        $projet = new Projet();
        $form = $this->createForm(ProjetType::class, $projet);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form['attachment']->getData();

            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

            // Move the file to the directory where brochures are stored
            try {
                $file->move("/opt/www/portfolio/web/images",
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
                dump($e);
            }

            $projet->setImageProjet($fileName);
            $em = $this->getDoctrine()->getManager();
            $em->persist($projet);
            $em->flush();

            return $this->redirectToRoute('dashboard');

        }


        return $this->render('projet/newProjet.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
