<?php

namespace AppBundle\Repository;

/**
 * DescriptionGeneralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptionGeneralRepository extends \Doctrine\ORM\EntityRepository
{
}
