<?php

namespace AppBundle\Repository;

/**
 * EmailInterestedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailInterestedRepository extends \Doctrine\ORM\EntityRepository
{
}
