<?php

namespace AppBundle\Repository;

/**
 * LienSociauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LienSociauxRepository extends \Doctrine\ORM\EntityRepository
{
}
