app_lien_sociaux:
    resource: "@AppBundle/Controller/LienSociauxController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
